/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/storage/public-objects/{filePath}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve a public asset file
         * @description Streams a file from the configured public-objects GCS search paths.
         *     The caller must know the exact filename. No authentication required.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Relative path of the file (e.g. `logos/sample.png`).
                     *     The path may contain forward slashes for nested directories.
                     *     OpenAPI 3.x does not natively model wildcard path segments —
                     *     this parameter represents the full remainder of the URL path.
                     */
                    filePath: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description File contents streamed with original Content-Type */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description File not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/org-logo/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve an org logo
         * @description Returns the logo image for the given account. No authentication required.
         *
         *     The underlying GCS object is stored at a random UUID path so guessing a
         *     valid `accountId` only returns the publicly-intended logo, never a private asset.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Numeric account / organisation ID */
                    accountId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Image data (PNG, JPEG, or WebP) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Account not found or no logo configured */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/settings/org": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get org settings (internal)
         * @description Returns the authenticated organisation's name, logo URL, and brand color.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Org settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            org?: components["schemas"]["OrgSettings"];
                        };
                    };
                };
                /** @description Missing or invalid session token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Account not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update org settings (internal)
         * @description Partially updates the org's display name and/or accent color.
         *     All fields are optional — omitted fields keep their current values.
         *     Send `clearLogo: true` to remove the current logo.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example West Hills Capital */
                        name?: string;
                        /** @example #C49A38 */
                        brandColor?: string;
                        clearLogo?: boolean;
                    };
                };
            };
            responses: {
                /** @description Updated org settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            org?: components["schemas"]["OrgSettings"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/product/settings/org": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get org settings
         * @description Returns the authenticated organisation's name, logo URL, and brand color.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Org settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            org?: components["schemas"]["OrgSettings"];
                        };
                    };
                };
                /** @description Missing or invalid Clerk JWT */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update org settings
         * @description Partially updates the org's display name and/or accent color.
         *     All fields are optional — omitted fields keep their current values.
         *     Send `clearLogo: true` to remove the current logo.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example Acme Capital */
                        name?: string;
                        /** @example #3B6CB7 */
                        brandColor?: string;
                        clearLogo?: boolean;
                    };
                };
            };
            responses: {
                /** @description Updated org settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            org?: components["schemas"]["OrgSettings"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/internal/settings/org/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload org logo (internal)
         * @description Replaces the organisation's logo with the uploaded image.
         *     Upload the raw image binary in the request body and set
         *     `Content-Type` to the image MIME type.
         *
         *     Maximum size: **5 MB**. Accepted types: `image/png`, `image/jpeg`, `image/webp`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "image/png": string;
                    "image/jpeg": string;
                    "image/webp": string;
                };
            };
            responses: {
                /** @description Updated org (with new logo_url) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            org?: components["schemas"]["OrgSettings"];
                        };
                    };
                };
                /** @description Unsupported MIME type or empty body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/settings/org/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload org logo
         * @description Replaces the organisation's logo with the uploaded image.
         *     Upload the raw image binary in the request body and set
         *     `Content-Type` to the image MIME type.
         *
         *     Maximum size: **5 MB**. Accepted types: `image/png`, `image/jpeg`, `image/webp`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "image/png": string;
                    "image/jpeg": string;
                    "image/webp": string;
                };
            };
            responses: {
                /** @description Updated org (with new logo_url) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            org?: components["schemas"]["OrgSettings"];
                        };
                    };
                };
                /** @description Unsupported MIME type or empty body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/settings/extract-brand-colors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract brand colors from a website (internal)
         * @description Fetches the given URL and extracts prominent brand colors from its CSS
         *     and inline styles. Returns an ordered list of hex color strings.
         *
         *     The endpoint refuses private/internal IP ranges (SSRF protection).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uri
                         * @example https://example.com
                         */
                        url: string;
                    };
                };
            };
            responses: {
                /** @description Extracted hex colors ordered by prominence */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @example [
                             *       "#1A2B3C",
                             *       "#C49A38"
                             *     ]
                             */
                            colors?: string[];
                        };
                    };
                };
                /** @description Could not fetch or parse the URL */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/settings/extract-brand-colors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract brand colors from a website
         * @description Fetches the given URL and extracts prominent brand colors from its CSS
         *     and inline styles. Returns an ordered list of hex color strings.
         *
         *     The endpoint refuses private/internal IP ranges (SSRF protection).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uri
                         * @example https://example.com
                         */
                        url: string;
                    };
                };
            };
            responses: {
                /** @description Extracted hex colors ordered by prominence */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @example [
                             *       "#1A2B3C",
                             *       "#3B6CB7"
                             *     ]
                             */
                            colors?: string[];
                        };
                    };
                };
                /** @description Could not fetch or parse the URL */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/docufill/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List packages
         * @description Returns all Docuplete packages configured for the authenticated account, ordered by most-recently updated first.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of packages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            packages: components["schemas"]["DocuFillPackage"][];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/docufill/packages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a package
         * @description Returns a single Docuplete package by its numeric ID. The package must belong to the authenticated account.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Numeric package ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Package found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            package: components["schemas"]["DocuFillPackage"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Package not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/docufill/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sessions
         * @description Returns a paginated list of interview sessions for the authenticated account.
         *     Filter by package, status, or both. Results are ordered newest-first.
         *
         *     When `dealId` is supplied instead, returns the single most-recent session
         *     for that deal (legacy behavior used by the internal portal).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter sessions to a specific package ID */
                    packageId?: number;
                    /** @description Filter sessions by status */
                    status?: "draft" | "in_progress" | "generated";
                    /** @description Maximum number of sessions to return */
                    limit?: number;
                    /** @description Number of sessions to skip (for pagination) */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated session list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            sessions: components["schemas"]["DocuFillSessionListItem"][];
                            /** @description Total number of sessions matching the filters (before pagination) */
                            total: number;
                        };
                    };
                };
                /** @description Invalid status value */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create an interview session
         * @description Creates a new Docuplete interview session for the specified package.
         *     Returns the session record and a bearer token used to load and submit
         *     the public-facing interview form. Sessions expire after **90 days**.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description ID of an active Docuplete package
                         * @example 7
                         */
                        packageId: number;
                        dealId?: number | null;
                        custodianId?: number | null;
                        depositoryId?: number | null;
                        transactionScope?: string | null;
                        source?: string;
                        prefill?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Session created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            session?: components["schemas"]["DocuFillSession"];
                            token?: string;
                        };
                    };
                };
                /** @description Invalid packageId or package not active */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Package not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/docufill/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an interview session (internal)
         * @description Creates a new Docuplete interview session for the specified package.
         *     Returns the session record and a bearer token used to load and submit
         *     the public-facing interview form. Sessions expire after **90 days**.
         *
         *     Pass `testMode: true` to create a test session without requiring the
         *     package to be active (requires an authenticated admin account).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description ID of an active Docuplete package
                         * @example 7
                         */
                        packageId: number;
                        /** @description Optional deal ID to associate with this session */
                        dealId?: number | null;
                        /** @description Override the package's default custodian */
                        custodianId?: number | null;
                        /** @description Override the package's default depository */
                        depositoryId?: number | null;
                        /** @description Override the package's transaction scope */
                        transactionScope?: string | null;
                        /**
                         * @description Free-text label for how this session was created
                         * @default deal_builder
                         */
                        source?: string;
                        /** @description Initial field values to pre-populate in the interview */
                        prefill?: {
                            [key: string]: unknown;
                        };
                        /**
                         * @description Create a non-production test session (admin only)
                         * @default false
                         */
                        testMode?: boolean;
                    };
                };
            };
            responses: {
                /** @description Session created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            session?: components["schemas"]["DocuFillSession"];
                            /** @description Bearer token passed to the public interview form */
                            token?: string;
                        };
                    };
                };
                /** @description Invalid packageId, scope mismatch, or package not active */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Package not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/docufill/sessions/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a session
         * @description Returns the full interview session by its opaque token. Includes answers, fields, documents, prefill data, and package metadata.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Opaque session token (e.g. `df_abc123`) returned when the session was created */
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            session: components["schemas"]["DocuFillSession"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Session not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docufill/public/sessions/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Load an interview session
         * @description Returns the full session object including package metadata, document list,
         *     field definitions, prefill data, and saved answers. No authentication required.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Opaque session token returned when the session was created */
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            session?: components["schemas"]["DocuFillSession"];
                        };
                    };
                };
                /** @description Session not found or expired */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Save interview answers
         * @description Persists a partial or complete answers object for the session. Optionally
         *     updates the session status (e.g. `in_progress`). The session must not have expired.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Map of fieldId → value pairs */
                        answers?: {
                            [key: string]: unknown;
                        };
                        /**
                         * @description Optional status update
                         * @enum {string}
                         */
                        status?: "draft" | "in_progress";
                    };
                };
            };
            responses: {
                /** @description Updated session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            session?: components["schemas"]["DocuFillSession"];
                        };
                    };
                };
                /** @description Session not found or expired */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/docufill/public/sessions/{token}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate the document packet
         * @description Validates the saved answers, renders each document as a filled PDF,
         *     bundles them into a single packet PDF, and (when configured) uploads
         *     the packet to Google Drive. Returns a download URL for the packet.
         *
         *     The session status is set to `generated`. The session must not have expired.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Packet generated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Summary of generated documents */
                            packet?: Record<string, never>;
                            /** @example /api/v1/docufill/public/sessions/df_abc123/packet.pdf */
                            downloadUrl?: string;
                            drive?: {
                                fileId?: string;
                                url?: string;
                            } | null;
                            warnings?: string[];
                        };
                    };
                };
                /** @description Validation failed — required fields are missing or invalid */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Session not found or expired */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docufill/public/sessions/{token}/packet.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the generated packet as PDF
         * @description Returns the fully-filled packet PDF for display or download.
         *     The packet is rendered on demand from the latest saved answers — it
         *     does not require a prior `/generate` call, but all required fields
         *     must be complete.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PDF binary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                    };
                };
                /** @description Session not found or expired */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deals/{id}/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Mark payment as received
         * @description Records the current timestamp as `payment_received_at` for the deal.
         *     No request body is needed. Idempotent — calling it again updates the timestamp.
         *
         *     Use `/wire-received` instead when the payment method is a bank wire, as that
         *     endpoint also sets `wire_received_at` and triggers the wire confirmation email.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payment timestamp recorded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            /** Format: date-time */
                            paymentReceivedAt?: string;
                        };
                    };
                };
                /** @description Deal not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/deals/{id}/wire-received": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Mark wire payment received
         * @description Records the current timestamp as `wire_received_at` (and also sets
         *     `payment_received_at` if not already set). Sends the wire confirmation
         *     email to the customer — email sending is idempotent (only fires once per deal).
         *     No request body is needed.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Wire timestamp recorded and confirmation email sent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            /** Format: date-time */
                            wireReceivedAt?: string;
                            /** Format: date-time */
                            wireConfirmationEmailSentAt?: string | null;
                        };
                    };
                };
                /** @description Deal not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/deals/{id}/tracking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set shipment tracking number
         * @description Stores the carrier tracking number and schedules a shipping notification
         *     email to the customer for 24 hours from now. The `trackingNumber` field
         *     is required and must be non-empty.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 1Z999AA10123456784 */
                        trackingNumber: string;
                    };
                };
            };
            responses: {
                /** @description Tracking number saved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            trackingNumber?: string;
                            /** Format: date-time */
                            shippingNotificationScheduledAt?: string;
                        };
                    };
                };
                /** @description Missing or empty trackingNumber */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Deal not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/product/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current account
         * @description Returns account and user information for the authenticated session.
         *     Accepts both Clerk JWTs and API keys (`sk_live_...`).
         *
         *     When authenticated via API key, `email` is `null` (keys are account-scoped,
         *     not user-scoped) and `role` is `"member"`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account info */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountInfo"];
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Account not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/auth/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List API keys
         * @description Returns all API keys (active and revoked) for the authenticated account. Plaintext keys are never returned — only the prefix and metadata.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of API keys */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            keys?: components["schemas"]["ApiKey"][];
                        };
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create an API key
         * @description Creates a new API key scoped to the authenticated account.
         *     The full plaintext key is returned **once** and cannot be retrieved again — store it securely.
         *     Keys are prefixed with `sk_live_` and are stored as a SHA-256 hash.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Human-readable label for the key (max 100 characters).
                         * @example Production integration
                         */
                        name: string;
                    };
                };
            };
            responses: {
                /** @description API key created. The `key` field contains the plaintext key — shown only once. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            name?: string;
                            /**
                             * @description Full plaintext API key. Store securely — not shown again.
                             * @example sk_live_a1b2c3d4e5f6…
                             */
                            key?: string;
                            /** @example sk_live_a1b2c3 */
                            keyPrefix?: string;
                            /** Format: date-time */
                            createdAt?: string;
                            note?: string;
                        };
                    };
                };
                /** @description Missing or invalid name */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Maximum key limit reached */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/auth/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke an API key
         * @description Soft-revokes an API key. Revoked keys are rejected immediately. Only keys belonging to the authenticated account can be revoked.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The numeric ID of the API key to revoke. */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Key revoked */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                            id?: number;
                        };
                    };
                };
                /** @description Invalid key id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Key not found or already revoked */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OrgSettings: {
            id?: number;
            /** @example Acme Capital */
            name?: string;
            /** @example acme-capital */
            slug?: string;
            /** @example /api/storage/org-logo/42 */
            logo_url?: string | null;
            /**
             * @description Six-digit hex accent color
             * @example #C49A38
             */
            brand_color?: string;
        };
        /** @description A Docuplete package — a reusable interview template that defines the documents, fields, and configuration for a document workflow. */
        DocuFillPackage: {
            /** @example 7 */
            id: number;
            account_id?: number;
            /** @example IRA Rollover Packet */
            name: string;
            /** @description Only active packages can have sessions created against them. */
            active: boolean;
            description?: string | null;
            /** @example IRA */
            transaction_scope?: string | null;
            custodian_id?: number | null;
            custodian_name?: string | null;
            depository_id?: number | null;
            depository_name?: string | null;
            /** Format: uri */
            webhook_url?: string | null;
            /** Format: email */
            recipient_email?: string | null;
            fields?: Record<string, never>[];
            documents?: Record<string, never>[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @description A lightweight session summary returned by the session list endpoint. */
        DocuFillSessionListItem: {
            id: number;
            /** @example df_abc123 */
            token: string;
            package_id: number;
            package_name: string;
            /** @enum {string} */
            status: "draft" | "in_progress" | "generated";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            expires_at: string;
        };
        /** @description Account and user information returned by the `/product/auth/me` endpoint. */
        AccountInfo: {
            /** @description Numeric account ID. */
            accountId: number;
            /**
             * @description Display name of the account.
             * @example Acme Capital
             */
            accountName: string;
            /**
             * @description URL-safe account slug.
             * @example acme-capital
             */
            slug: string;
            /**
             * Format: email
             * @description Email of the authenticated user. `null` when authenticated via API key.
             */
            email?: string | null;
            /**
             * @description Role of the authenticated user within the account.
             * @enum {string}
             */
            role: "admin" | "member";
        };
        DocuFillSession: {
            id?: number;
            /** @example df_abc123 */
            token?: string;
            package_id?: number;
            package_name?: string;
            /** @enum {string} */
            status?: "draft" | "in_progress" | "generated";
            answers?: {
                [key: string]: unknown;
            };
            prefill?: {
                [key: string]: unknown;
            };
            fields?: Record<string, never>[];
            documents?: Record<string, never>[];
            mappings?: Record<string, never>[];
            custodian_name?: string | null;
            depository_name?: string | null;
            org_name?: string | null;
            org_logo_url?: string | null;
            /** @example #C49A38 */
            org_brand_color?: string | null;
            transaction_scope?: string | null;
            /** Format: date-time */
            expires_at?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ApiKey: {
            /** @example 1 */
            id?: number;
            /** @example Production integration */
            name?: string;
            /**
             * @description First 16 characters of the key — shown for identification only.
             * @example sk_live_a1b2c3
             */
            keyPrefix?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            revokedAt?: string | null;
            active?: boolean;
        };
        Error: {
            error: string;
        };
        /**
         * @description The JSON body delivered to your webhook endpoint when a Docuplete form is submitted. Every delivery is signed — verify the `X-Docuplete-Signature` header before processing.
         *
         *     **Signature verification**
         *
         *     Each request includes:
         *     ```
         *     X-Docuplete-Signature: sha256=<hex>
         *     ```
         *     Verify by computing `HMAC-SHA256(webhookSecret, rawBody)` using your package's signing secret (available in the Docuplete dashboard under Webhooks → Signing secret).
         *
         *     **Node.js example**
         *     ```js
         *     const crypto = require('crypto');
         *     const sig = req.headers['x-docuplete-signature'];
         *     const expected = 'sha256=' + crypto.createHmac('sha256', WEBHOOK_SECRET).update(rawBody).digest('hex');
         *     if (!crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected))) {
         *       return res.status(401).end('Invalid signature');
         *     }
         *     ```
         */
        WebhookPayload: {
            /**
             * @description `interview.submitted` fires on every completed form submission. `interview.test` is sent when you click **Send test** in the dashboard.
             * @enum {string}
             */
            event: "interview.submitted" | "interview.test";
            /** @description Internal ID of the Docuplete package. */
            package_id: number;
            /** @description Human-readable name of the package. */
            package_name: string;
            /** @description Unique submission token. Use this as an idempotency key — automatic retries deliver the same token. */
            token: string;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp of when the form was submitted.
             */
            submitted_at: string;
            /** @description Key-value map of field IDs to their submitted values. Fields marked sensitive in the package settings are replaced with `[redacted]`. */
            answers: {
                [key: string]: string;
            };
        };
        /** @description A single webhook delivery attempt recorded in the delivery log. */
        WebhookDelivery: {
            id: number;
            /** @enum {string} */
            event_type: "interview.submitted" | "interview.test";
            /** @description 1 for the initial attempt; increments for each automatic retry (max 4 attempts total: immediate, +5 s, +30 s, +5 min). */
            attempt_number: number;
            /** @description HTTP status returned by the endpoint, or null if the request failed to connect. */
            http_status: number | null;
            /** @description First 1 KB of the response body, useful for debugging. */
            response_body: string;
            /** @description Round-trip time in milliseconds. */
            duration_ms: number;
            /** Format: date-time */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
