// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/acroform-review/AcroFormFlow.tsx": () => import("../components/mockups/acroform-review/AcroFormFlow.tsx"),
  "./components/mockups/acroform-review/FieldReview.tsx": () => import("../components/mockups/acroform-review/FieldReview.tsx"),
  "./components/mockups/acroform-review/ReviewStats.tsx": () => import("../components/mockups/acroform-review/ReviewStats.tsx"),
  "./components/mockups/acroform-review/VisualMapper.tsx": () => import("../components/mockups/acroform-review/VisualMapper.tsx"),
  "./components/mockups/docufill-layouts/CommandDeck.tsx": () => import("../components/mockups/docufill-layouts/CommandDeck.tsx"),
  "./components/mockups/docufill-layouts/LeftRailNav.tsx": () => import("../components/mockups/docufill-layouts/LeftRailNav.tsx"),
  "./components/mockups/docufill-layouts/MasterDetail.tsx": () => import("../components/mockups/docufill-layouts/MasterDetail.tsx"),
  "./components/mockups/hero-variants/GoldHero.tsx": () => import("../components/mockups/hero-variants/GoldHero.tsx"),
  "./components/mockups/hero-variants/GradientHero.tsx": () => import("../components/mockups/hero-variants/GradientHero.tsx"),
  "./components/mockups/hero-variants/LargerHero.tsx": () => import("../components/mockups/hero-variants/LargerHero.tsx"),
  "./components/mockups/logo-variants/LogoA.tsx": () => import("../components/mockups/logo-variants/LogoA.tsx"),
  "./components/mockups/logo-variants/LogoB.tsx": () => import("../components/mockups/logo-variants/LogoB.tsx"),
  "./components/mockups/logo-variants/LogoC.tsx": () => import("../components/mockups/logo-variants/LogoC.tsx"),
  "./components/mockups/logo-variants/LogoD.tsx": () => import("../components/mockups/logo-variants/LogoD.tsx"),
  "./components/mockups/whc-internal/PolishedWarmth.tsx": () => import("../components/mockups/whc-internal/PolishedWarmth.tsx"),
  "./components/mockups/whc-internal/StructuredPrecision.tsx": () => import("../components/mockups/whc-internal/StructuredPrecision.tsx")
};
