// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/whc-internal/PolishedWarmth.tsx": () => import("../components/mockups/whc-internal/PolishedWarmth.tsx"),
  "./components/mockups/whc-internal/StructuredPrecision.tsx": () => import("../components/mockups/whc-internal/StructuredPrecision.tsx"),
  "./components/mockups/docufill-layouts/CommandDeck.tsx": () => import("../components/mockups/docufill-layouts/CommandDeck.tsx"),
  "./components/mockups/docufill-layouts/LeftRailNav.tsx": () => import("../components/mockups/docufill-layouts/LeftRailNav.tsx"),
  "./components/mockups/docufill-layouts/MasterDetail.tsx": () => import("../components/mockups/docufill-layouts/MasterDetail.tsx")
};
