import {
  pgTable, serial, text, integer, boolean, timestamp, numeric, jsonb, date,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const appointments = pgTable("appointments", {
  id: serial("id").primaryKey(),
  confirmationId: text("confirmation_id").notNull().unique(),
  slotId: text("slot_id").notNull(),
  scheduledTime: timestamp("scheduled_time", { withTimezone: true }).notNull(),
  dayLabel: text("day_label").notNull(),
  timeLabel: text("time_label").notNull(),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  state: text("state").notNull(),
  allocationType: text("allocation_type").notNull(),
  allocationRange: text("allocation_range").notNull(),
  timeline: text("timeline").notNull(),
  status: text("status").notNull().default("confirmed"),
  calendarEventId: text("calendar_event_id"),
  leadId: integer("lead_id"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex("appointments_slot_id_confirmed_idx")
    .on(t.slotId)
    .where(sql`status = 'confirmed'`),
]);

export const leads = pgTable("leads", {
  id: serial("id").primaryKey(),
  formType: text("form_type").notNull(),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone"),
  state: text("state"),
  allocationType: text("allocation_type"),
  allocationRange: text("allocation_range"),
  timeline: text("timeline"),
  currentCustodian: text("current_custodian"),
  ipAddress: text("ip_address"),
  status: text("status").notNull().default("new"),
  notes: text("notes"),
  followUpDate: date("follow_up_date"),
  owner: text("owner"),
  linkedConfirmationId: text("linked_confirmation_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const bookingAttempts = pgTable("booking_attempts", {
  id: serial("id").primaryKey(),
  attemptedAt: timestamp("attempted_at", { withTimezone: true }).notNull().defaultNow(),
  email: text("email").notNull(),
  slotId: text("slot_id").notNull(),
  ipAddress: text("ip_address"),
  success: boolean("success").notNull(),
  confirmationId: text("confirmation_id"),
  errorCode: text("error_code"),
  errorDetail: text("error_detail"),
});

export const spotPriceHistory = pgTable("spot_price_history", {
  id: serial("id").primaryKey(),
  goldBid: numeric("gold_bid", { precision: 12, scale: 4 }),
  goldAsk: numeric("gold_ask", { precision: 12, scale: 4 }),
  silverBid: numeric("silver_bid", { precision: 12, scale: 4 }),
  silverAsk: numeric("silver_ask", { precision: 12, scale: 4 }),
  source: text("source"),
  recordedAt: timestamp("recorded_at", { withTimezone: true }).notNull().defaultNow(),
});

export const contentArticles = pgTable("content_articles", {
  id: serial("id").primaryKey(),
  slug: text("slug").notNull().unique(),
  title: text("title").notNull(),
  excerpt: text("excerpt").notNull(),
  groupId: text("group_id").notNull().default("making-smart-decisions"),
  metaDescription: text("meta_description").notNull().default(""),
  sections: jsonb("sections").notNull().default([]),
  related: jsonb("related").notNull().default([]),
  status: text("status").notNull().default("draft"),
  publishedAt: timestamp("published_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const deals = pgTable("deals", {
  id: serial("id").primaryKey(),
  leadId: integer("lead_id"),
  confirmationId: text("confirmation_id"),
  dealType: text("deal_type").notNull().default("cash"),
  iraType: text("ira_type"),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone"),
  state: text("state"),
  custodian: text("custodian"),
  custodianId: integer("custodian_id"),
  depository: text("depository"),
  depositoryId: integer("depository_id"),
  iraAccountNumber: text("ira_account_number"),
  goldSpotAsk: numeric("gold_spot_ask", { precision: 12, scale: 4 }),
  silverSpotAsk: numeric("silver_spot_ask", { precision: 12, scale: 4 }),
  spotTimestamp: timestamp("spot_timestamp", { withTimezone: true }),
  products: jsonb("products"),
  subtotal: numeric("subtotal", { precision: 12, scale: 2 }),
  shipping: numeric("shipping", { precision: 12, scale: 2 }),
  total: numeric("total", { precision: 12, scale: 2 }),
  balanceDue: numeric("balance_due", { precision: 12, scale: 2 }),
  shippingMethod: text("shipping_method").default("fedex_hold"),
  fedexLocation: text("fedex_location"),
  notes: text("notes"),
  status: text("status").notNull().default("locked"),
  lockedAt: timestamp("locked_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  shipToName: text("ship_to_name"),
  shipToLine1: text("ship_to_line1"),
  shipToCity: text("ship_to_city"),
  shipToState: text("ship_to_state"),
  shipToZip: text("ship_to_zip"),
  externalTradeId: text("external_trade_id"),
  supplierConfirmationId: text("supplier_confirmation_id"),
  executionStatus: text("execution_status"),
  executionTimestamp: timestamp("execution_timestamp", { withTimezone: true }),
  invoiceId: text("invoice_id"),
  invoiceUrl: text("invoice_url"),
  invoiceGeneratedAt: timestamp("invoice_generated_at", { withTimezone: true }),
  recapEmailSentAt: timestamp("recap_email_sent_at", { withTimezone: true }),
  billingLine1: text("billing_line1"),
  billingLine2: text("billing_line2"),
  billingCity: text("billing_city"),
  billingState: text("billing_state"),
  billingZip: text("billing_zip"),
  fedexLocationHours: text("fedex_location_hours"),
  termsProvided: boolean("terms_provided"),
  termsProvidedAt: timestamp("terms_provided_at", { withTimezone: true }),
  termsVersion: text("terms_version"),
  confirmationMethod: text("confirmation_method"),
  paymentReceivedAt: timestamp("payment_received_at", { withTimezone: true }),
  trackingNumber: text("tracking_number"),
  orderPlacedAt: timestamp("order_placed_at", { withTimezone: true }),
  executionWarnings: jsonb("execution_warnings").default([]),
  wireReceivedAt: timestamp("wire_received_at", { withTimezone: true }),
  orderPaidAt: timestamp("order_paid_at", { withTimezone: true }),
  shippedAt: timestamp("shipped_at", { withTimezone: true }),
  deliveredAt: timestamp("delivered_at", { withTimezone: true }),
  shippingNotificationScheduledAt: timestamp("shipping_notification_scheduled_at", { withTimezone: true }),
  shippingEmailSentAt: timestamp("shipping_email_sent_at", { withTimezone: true }),
  deliveryEmailSentAt: timestamp("delivery_email_sent_at", { withTimezone: true }),
  followUp7dScheduledAt: timestamp("follow_up_7d_scheduled_at", { withTimezone: true }),
  followUp30dScheduledAt: timestamp("follow_up_30d_scheduled_at", { withTimezone: true }),
  followUp7dSentAt: timestamp("follow_up_7d_sent_at", { withTimezone: true }),
  followUp30dSentAt: timestamp("follow_up_30d_sent_at", { withTimezone: true }),
  wireConfirmationEmailSentAt: timestamp("wire_confirmation_email_sent_at", { withTimezone: true }),
});
